### ISSUE TITLE
AnsibleFileNotFound: Could not find or access '/etc/cfssl/ca-etcd.pem'

### ISSUE THREAD

**Issue by tscolari** [githubixx/ansible-role-etcd#3]
Hi there,

I've been following your ansible+kubernetes guide and when it's time to run this script I'm getting this error on all hosts:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/etc/cfssl/ca-etcd.pem'
failed: [k8s-node-1.my-host.com] (item=ca-etcd.pem) => {"changed": false, "item": "ca-etcd.pem", "msg": "Could not find or access '/etc/cfssl/ca-etcd.pem'"}
```

do you have an idea what could be?
my certificates were generated in `~/.k8s/certs` using:

```
k8s_ca_conf_directory: "{{ '~/.k8s/certs' | expanduser }}"
```

in `group_vars/all` (and they are there!)

**Comment by githubixx** [comment]
Hi,
hmmm... That's pretty strange. In my setup I also defined `k8s_ca_conf_directory` in `group_vars/all`. And I just updated and tested the role a few days ago. The directory `/etc/cfssl/` was used in a earlier version as default value for `k8s_ca_conf_directory`. Also the task which copies the the certificates to the destination is pretty simple:

```
- name: Copy certificates
  copy:
    src: "{{k8s_ca_conf_directory}}/{{item}}"
    dest: "{{etcd_conf_dir}}/{{item}}"
    mode: 0640
    owner: root
    group: root
  with_items:
    - "{{etcd_certificates}}"
  tags:
    - etcd
```
So I suspect that somewhere `k8s_ca_conf_directory: "/etc/cfssl"` is defined in your setup which overrides your setting. Please run `fgrep -R "/etc/cfssl" *` in your Ansible `roles_path` directory (or directories) and see if it matches somewhere. If so please remove the entry and try rolling out the role again.
