### ISSUE TITLE
Task "Downloading official etcd release" saves file with wrong filename

### ISSUE THREAD

**Issue by WilliamCocker** [githubixx/ansible-role-etcd#5]
The task "Downloading official etcd release" only specifies a destination directory without a filename :

```
- name: Downloading official etcd release
  get_url:
    url: https://github.com/coreos/etcd/releases/download/v{{etcd_version}}/etcd-v{{etcd_version}}-linux-amd64.tar.gz
    dest: "{{etcd_download_dir}}"
    mode: 0755
  tags:
    - etcd
```

As a result, the filename is not as expected by the next task "Unzip downloaded file" which then crashes:
![screen shot 2018-05-14 at 14 00 53](https://user-images.githubusercontent.com/37018962/40001165-e1c25460-578d-11e8-987d-0026c9cc3da8.png)

![screen shot 2018-05-14 at 15 50 11](https://user-images.githubusercontent.com/37018962/40001472-86b8cc2e-578e-11e8-9d97-5476b9e6be02.png)

A simple fix is to specify the full filename in the dest parameter such as this:

```
    dest: "{{etcd_download_dir}}/etcd-v{{etcd_version}}-linux-amd64.tar.gz"
```

I ran into this problem on a **btrfs** filesystem, it might not be a problem on **ext4**.
