### ISSUE TITLE
Task "Unzip downloaded file" crashes trying to change ownership to unexisting user/group

### ISSUE THREAD

**Issue by WilliamCocker** [githubixx/ansible-role-etcd#6]
The "Unzip downloaded file" crashes as it tries to set the ownership of files and directories back to their original values. The original user and group do not exist and thus the task crashes. 

```
- name: Unzip downloaded file
  unarchive:
    src: "{{etcd_download_dir}}/etcd-v{{etcd_version}}-linux-amd64.tar.gz"
    dest: "{{etcd_download_dir}}/"
    remote_src: yes
    creates: "{{etcd_download_dir}}/etcd-v{{etcd_version}}-linux-amd64/etcd"
  tags:
    - etcd
```

![screen shot 2018-05-14 at 15 18 14](https://user-images.githubusercontent.com/37018962/40001768-3441aa1e-578f-11e8-8b09-fafc22138ec7.png)

A second playbook run "fixes" the problem as the task is then skipped and other tasks can go on (there is no real ownership problem).

So maybe the owner and group could be set by the task or the error ignored? What is the best option here in your opinion?

I should mention I ran into this problem on a **btrfs** filesystem, maybe the behaviour is different on **ext4**.
